build:
	cd src && javac com\summer_practice_2015\team13\helloex_0\Printer.java
	cd src && javac com\summer_practice_2015\team13\helloex_0\Main.java

clean:
	del src\com\summer_practice_2015\team13\helloex_0\*.class

run:
	java -cp src com.summer_practice_2015.team13.helloex_0.Main